brew 'cmake'
brew 'enchant'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'historian'
brew 'mas'
brew 'mercurial'
brew 'node'
brew 'openconnect'
brew 'openssl@1.1'
brew 'openssl'
brew 'pyenv'
brew 'pyenv-virtualenvwrapper'
brew 'rust'
brew 'the_silver_searcher'
brew 'vim'
brew 'youtube-dl'
mas 'Airmail 3', id: 918858936
mas 'Microsoft Remote Desktop', id: 715768417
mas 'Pixelmator', id: 407963104
mas 'Textual', id: 896450579
mas 'Tweetbot', id: 557168941
mas 'Xcode', id: 497799835
tap 'caskroom/cask'
cask_args appdir: '/Applications'
cask '1password'
cask 'alfred'
cask 'dash'
cask 'divvy'
cask 'docker'
cask 'dropbox'
cask 'dropshare'
cask 'electrum'
cask 'firefox'
cask 'google-chrome'
cask 'istat-menus'
cask 'iterm2-nightly'
cask 'microsoft-office'
cask 'macvim'
cask 'origin'
cask 'plex-media-player'
cask 'screenhero'
cask 'skype'
cask 'slack'
cask 'steam'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'vmware-fusion'
cask 'wireshark'
cask 'zoomus'
tap 'caskroom/versions'
cask 'google-chrome-canary'
cask 'safari-technology-preview'
