brew 'automake'
brew 'ccextractor'
brew 'clang-format'
brew 'diff-so-fancy'
brew 'ffmpeg'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'godep'
brew 'historian'
brew 'mas'
brew 'mercurial'
brew 'mkvtoolnix'
brew 'node'
brew 'openssl@1.1'
brew 'openssl'
brew 'pyenv'
brew 'pyenv-virtualenvwrapper'
brew 'pypy3'
brew 'ripgrep'
brew 'rust'
brew 'shellcheck'
brew 'vim'
brew 'youtube-dl'
mas 'Airmail 3', id: 918858936
mas 'Microsoft Remote Desktop', id: 1295203466
mas 'PiPifier', id: 1160374471
mas 'Pixelmator', id: 407963104
mas 'Textual 7', id: 1262957439
mas 'WeChat', id: 836500024
mas 'Xcode', id: 497799835
tap 'caskroom/cask'
tap 'caskroom/versions'
cask_args appdir: '/Applications'
cask '1password'
cask 'alfred'
cask 'battle-net'
cask 'dash'
cask 'divvy'
cask 'docker'
cask 'dropshare'
cask 'expressvpn'
cask 'firefox'
cask 'google-chrome'
cask 'imageoptim'
cask 'intel-power-gadget' # used with istat
cask 'istat-menus'
cask 'iterm2-nightly'
cask 'java'
cask 'macvim'
cask 'microsoft-office'
cask 'openemu'
cask 'origin'
cask 'paw'
cask 'sabnzbd'
cask 'safari-technology-preview'
cask 'signal'
cask 'skype'
cask 'slack'
cask 'steam'
cask 'torbrowser'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'vmware-fusion'
cask 'wireshark'
cask 'zoomus'
